
def exceptions(execution, context):
    pass